### PR TITLE
feat(build): create distroless docker image

### PR DESCRIPTION
**Pull request by meysam81**
supercedes #228

### CODE REVIEW

**Comment by dfoxg** [comment]
Thank you! 

Am I right, that the bash-script doesn´t work anymore, since there is no shell in distroless image?

**Comment by meysam81** [comment]
Yes, distroless images have no shell available.

The aim is to only spin up the server process. No other binary is available, reducing the attack surface.
More information is available at the upstream repository: <https://github.com/GoogleContainerTools/distroless>

There are projects like [bash-static](https://github.com/robxu9/bash-static/), but I have never felt the need to have it included in my production deployments.

**Review by dfoxg — APPROVED** [review]
Thank you very much!

**Comment by dfoxg** [comment]
Sorry, i had to revert your changes. At least in my configuration, the reverse-proxy setup ([here](https://github.com/dfoxg/kratos-admin-ui/blob/main/kratos-admin-ui/deploy/nginx.conf#L34)) didnt worked anymore. If i got time i will debug it.

**Pull request merged**
